config/routes.rb
Rails.application.routes.draw do

  resources :tags
  root 'pages#index'

  resources :technologies do
    resources :histories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/technology.rb
class Technology < ApplicationRecord
  has_many :histories
  has_many :technology_tags
  has_many :tags, through: :technology_tags, dependent: :destroy

  validates(:name , presence: true, length:{ maximum: 50})
  validates(:year , numericality: {allow_blank: false, greater_than: 1900})
  validates(:month, numericality: {allow_blank: true, greater_than: 0, less_than:13})
  validates(:day  , numericality: {allow_blank: true, greater_than: 0, less_than:32})

  def save_tags(tags)

    return true if tags.nil?

    current_tags = self.tags.pluck(:name)
    old_tags = current_tags - tags;
    new_tags = tags - current_tags;

    # destroy old tags
    old_tags.each do |name|
      self.tags.delete Tag.find_by(name: name)
    end

    # create new tags
    new_tags.each do |name|
      next if name.empty?
      new_tag = Tag.find_or_create_by(name: name)
      self.tags << new_tag
    end

  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: [:new, :edit, :update, :create]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all.order(:year, :month, :day)
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
    @histories = @technology.histories.order(:year, :month, :day)
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        @technology.save_tags(params[:technology][:tags])
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        @technology.save_tags(params[:technology][:tags])
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Use by tag select box. use case are new, edit, create, update.
    def set_tags
      @tags = Tag.all.pluck(:name, :name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name, :description, :year, :month, :day)
    end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_with(model: technology, local: true, html: {class: "c-form"}) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :technology_name, class: "c-form__string" %>
  </div>
  <div class="field">
    <div><%= form.label "誕生日" %></div>
    <%= formYmd form %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :technology_description, class: "c-form__text" %>
  </div>
  <div class="field">
    <div><%= form.label "タグ" %></div>
    <%= select_tag(
      'technology[tags]',
      options_for_select(tags, technology.tags.pluck(:name)),
      { multiple: true, include_blank: true }
    ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<div class="contents__block -basic">
  <div class="main">
    <h1 class="main__title -h1">Editing Technology</h1>
    <%= render 'form', technology: @technology, tags: @tags %>
    <%= link_to '詳細', @technology %> |
    <%= link_to '戻る', technologies_path %>
  </div>
</div>

app/views/technologies/index.html.erb
<div class="contents__block -basic">
  <div class="main">
    <p id="notice"><%= notice %></p>

    <h1 class="main__title -h1">Technologies</h1>
    <%= link_to 'New Technology', new_technology_path %>

    <% @technologies.each do |t| %>
      <h2 class="main__title -h2"><%= link_to t.name, t %></h2>
      <%= render 'shared/tags', technology: t %>
      <h3 class="main__title -h3"><%= date(t.year, t.month, t.day) %>(<%= age(t.year, t.month, t.day) %>)</h3>


      <p><%= t.description %></p>
      [<%= link_to '編集', edit_technology_path(t) %>]
      [<%= link_to '削除', t, method: :delete, data: { confirm: 'Are you sure?' } %>]
    <% end %>



  </div>
</div>

app/views/technologies/new.html.erb
<div class="contents__block -basic">
  <div class="main">
    <h1 class="main__title -h1">New Technology</h1>
    <%= render 'form', technology: @technology, tags: @tags %>
    <%= link_to '戻る', technologies_path %>
  </div>
</div>

app/views/technologies/show.html.erb
<div class="contents__block -basic">
  <div class="main">

    <p id="notice"><%= notice %></p>

    <h1 class="main__title -h1"><%= @technology.name %></h1>
    <%= render 'shared/tags', technology: @technology %>
    <h2 class="main__title -h2"><%= date(@technology.year, @technology.month, @technology.day) %>(<%= age(@technology.year, @technology.month, @technology.day) %>)</h2>


    <p><%= simple_format @technology.description %></p>
    [<%= link_to '編集', edit_technology_path(@technology) %>]
    [<%= link_to '戻る', technologies_path %>]


    <h2 class="main__title -h2">歴史</h2>
    <%= link_to "New History", new_technology_history_path(@technology) %>
    <% if @technology.histories.any? %>
    <ul>
      <% @histories.each do |history| %>
      <li>
        <%= date(history.year, history.month, history.day) %>
        <%= link_to history.title, technology_history_path(@technology, history) %>
        <%= link_to(
          '[編集]',
          edit_technology_history_path(@technology, history)
        ) %>
        <%= link_to(
          '[✖]',
          technology_history_path(@technology, history),
          {
            method: :delete,
            class: 'command',
            data: { confirm: 'Sure?'}
          }
        ) %>
      </li>
      <% end %>
    </ul>
    <% end %>

    <%= form_for([@technology, @technology.histories.build]) do |f| %>
      <%= formYmd f %>
      <%= f.text_field(:title, {placeholder:'enter title'})  %>
      <%= f.submit %>
    <% end %>


    <script type="text/javascript">
    window.onload = function(){
      document.getElementById('history_year').focus();
    }
    </script>
  </div>
</div>